import Link from 'next/link';
import { PRODUCT_COPY } from '@/lib/identity/products';
import { getActiveProducts, requireCanonicalIdentity } from '@/lib/identity/server';

export default async function WorkspacesPage() {
  const { supabase } = await requireCanonicalIdentity();
  const entitlements = await getActiveProducts(supabase);
  return <main><div className="shell" style={{padding:'48px 0 72px'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Link href="/" className="eyebrow">Lead Emergence</Link><Link href="/account">Account</Link></header><section style={{padding:'12vh 0 48px'}}><p className="eyebrow" style={{color:'var(--teal)'}}>Welcome back</p><h1 className="serif" style={{fontSize:'clamp(2.2rem, 6vw, 4.6rem)',fontWeight:400,margin:'20px 0 14px'}}>Where are you leading today?</h1><p style={{fontSize:'1.1rem',lineHeight:1.7}}>Choose a product to continue. Each product owns its own roles and permissions.</p></section>{entitlements.length ? <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:18}}>{entitlements.map((product) => { const copy = PRODUCT_COPY[product]; return <article key={product} style={{border:'1px solid #d9d1c3',padding:26,background:'#fbf8f1'}}><p className="eyebrow" style={{color:'var(--gold)'}}>{product}</p><h2 className="serif" style={{fontSize:'1.6rem',fontWeight:400,margin:'18px 0 8px'}}>{copy.tagline}</h2><p style={{lineHeight:1.6,minHeight:76}}>{copy.description}</p><Link className="button" href={`/handoff/${product.toLowerCase()}`}>Open {copy.name} →</Link></article>; })}</div> : <section style={{borderTop:'1px solid #d9d1c3',borderBottom:'1px solid #d9d1c3',padding:'30px 0'}}><h2 className="serif" style={{fontWeight:400}}>Your Lead Emergence account is active.</h2><p>You do not currently have an active workspace.</p><div style={{display:'flex',gap:14,flexWrap:'wrap',marginTop:24}}><Link className="button secondary" href="/">Explore Lead Emergence</Link><Link className="button secondary" href="/account">Account settings</Link></div></section>}</div></main>;
}
