import Link from 'next/link';
import { redirect } from 'next/navigation';
import { PRODUCT_COPY } from '@/lib/identity/products';
import { getActiveProducts, requireCanonicalIdentity } from '@/lib/identity/server';

export default async function WorkspacesPage() {
  const { supabase } = await requireCanonicalIdentity();
  const entitlements = await getActiveProducts(supabase);
  if (entitlements.length === 1) redirect(`/handoff/${entitlements[0].toLowerCase()}`);

  return <main><div className="shell" style={{padding:'48px 0 72px'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Link href="/" className="eyebrow">Lead Emergence</Link><Link href="/account">Account</Link></header>{entitlements.length > 1 ? <section role="dialog" aria-modal="true" aria-labelledby="product-picker-title" style={{maxWidth:640,margin:'12vh auto',border:'1px solid #d9d1c3',padding:'clamp(28px,6vw,52px)',background:'#fbf8f1',boxShadow:'0 24px 70px rgba(37, 42, 35, .14)'}}><p className="eyebrow" style={{color:'var(--teal)'}}>One Lead Emergence sign-in</p><h1 id="product-picker-title" className="serif" style={{fontSize:'clamp(2.2rem, 6vw, 4rem)',fontWeight:400,margin:'18px 0 14px'}}>Where would you like to go?</h1><p style={{fontSize:'1.1rem',lineHeight:1.7,marginBottom:28}}>Your account has access to more than one Lead Emergence product. Choose one to continue.</p><div style={{display:'grid',gap:12}}>{entitlements.map((product) => { const copy = PRODUCT_COPY[product]; return <Link key={product} className="button" href={`/handoff/${product.toLowerCase()}`} style={{display:'flex',justifyContent:'space-between',alignItems:'center',textAlign:'left'}}><span><strong>{copy.name}</strong><span style={{display:'block',fontWeight:400,fontSize:'.9rem',marginTop:3}}>{copy.tagline}</span></span><span aria-hidden="true">→</span></Link>; })}</div><p style={{marginTop:24,fontSize:'.9rem'}}><Link href="/account">Manage your account</Link></p></section> : <section style={{maxWidth:680,margin:'12vh auto',borderTop:'1px solid #d9d1c3',borderBottom:'1px solid #d9d1c3',padding:'30px 0'}}><p className="eyebrow" style={{color:'var(--teal)'}}>Lead Emergence</p><h1 className="serif" style={{fontSize:'clamp(2.2rem, 6vw, 4rem)',fontWeight:400}}>Your account is active.</h1><p style={{fontSize:'1.1rem',lineHeight:1.7}}>You do not currently have access to a Lead Emergence product.</p><div style={{display:'flex',gap:14,flexWrap:'wrap',marginTop:24}}><Link className="button secondary" href="/">Explore Lead Emergence</Link><Link className="button secondary" href="/account">Account settings</Link></div></section>}</div></main>;
}
